import json
import functools
import sqlite3

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy import select, func, distinct
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.core.database import get_db
from app.models.expression import ExpressionSummary
from app.models.plof import PLOFAssociation, GeneDosageSensitivity
from app.schemas.expression import CellTypeExpression
from app.schemas.plof import PLOFAssociationSchema, GeneDosageSensitivitySchema
from app.schemas.safety import (
    SafetyCard,
    ExpressionSummaryForCard,
    PLOFSummaryForCard,
    GeneSearchResult,
    GeneSHAP,
    ShapFeature,
    ScoreDistribution,
)

router = APIRouter(prefix="/targets", tags=["targets"])

# Path to the pre-computed SHAP JSON (generated by data/export_shap_dr.py)
_SHAP_JSON_PATH = settings.data_dir / "safety_model_output" / "dr" / "gene_shap_dr.json"
_SHAP_FEATURES_DB = settings.data_dir / "safety_model_output" / "dr" / "gene_shap_features.db"


@functools.lru_cache(maxsize=1)
def _load_shap_metadata() -> dict:
    """Load gene SHAP metadata into memory (~5 MB), offload features to SQLite.

    The full JSON is ~455 MB and expands to >1 GB as Python dicts.  Only the
    ``features`` arrays are large; every other field is a scalar.  We keep
    scalars in RAM and write features to a SQLite file so the /safety-shap
    endpoint can look up a single gene on demand without holding everything
    in memory.
    """
    if not _SHAP_JSON_PATH.exists():
        return {}
    with open(_SHAP_JSON_PATH) as f:
        raw = json.load(f)

    # Build per-gene feature store on disk (one-time at startup)
    conn = sqlite3.connect(str(_SHAP_FEATURES_DB))
    conn.execute("DROP TABLE IF EXISTS shap_features")
    conn.execute(
        "CREATE TABLE shap_features (gene TEXT PRIMARY KEY, features TEXT)"
    )
    conn.executemany(
        "INSERT INTO shap_features VALUES (?, ?)",
        ((gene, json.dumps(entry.get("features", []), separators=(",", ":")))
         for gene, entry in raw.items()),
    )
    conn.commit()
    conn.close()

    # Return metadata only (strip features)
    return {
        gene: {k: v for k, v in entry.items() if k != "features"}
        for gene, entry in raw.items()
    }


def _load_gene_features(gene_symbol: str) -> list | None:
    """Look up SHAP features for a single gene from the on-disk SQLite store."""
    if not _SHAP_FEATURES_DB.exists():
        return None
    conn = sqlite3.connect(str(_SHAP_FEATURES_DB))
    row = conn.execute(
        "SELECT features FROM shap_features WHERE gene = ?", (gene_symbol,)
    ).fetchone()
    conn.close()
    if row is None:
        return None
    return json.loads(row[0])


def _dr_risk_class(shap_entry: dict | None, loeuf_fallback: str = "moderate") -> str:
    """Compute risk class from DR model score, matching safety-card logic."""
    if shap_entry is None:
        return loeuf_fallback
    is_drugged = bool(shap_entry.get("is_drugged", False))
    has_safety_event = shap_entry.get("has_safety_event")
    hp_score = shap_entry.get("safety_score")
    if is_drugged and has_safety_event is True:
        return "high"
    if hp_score is not None:
        if hp_score >= 0.70:
            return "high"
        elif hp_score >= 0.50:
            return "moderate"
        else:
            return "low"
    return loeuf_fallback


@functools.lru_cache(maxsize=1)
def _compute_score_distribution() -> ScoreDistribution:
    """Pre-compute histogram bins for the global safety score distribution."""
    import math
    data = _load_shap_metadata()
    n_bins = 20
    bin_edges = [round(i / n_bins, 4) for i in range(n_bins + 1)]

    drugged_safety   = [0] * n_bins
    drugged_no_safety = [0] * n_bins
    undrugged        = [0] * n_bins

    for entry in data.values():
        score = entry.get("safety_score")
        if score is None:
            continue
        bin_idx = min(int(math.floor(score * n_bins)), n_bins - 1)
        if entry.get("is_drugged"):
            if entry.get("has_safety_event") is True:
                drugged_safety[bin_idx] += 1
            else:
                drugged_no_safety[bin_idx] += 1
        else:
            undrugged[bin_idx] += 1

    return ScoreDistribution(
        bins=bin_edges,
        drugged_safety=drugged_safety,
        drugged_no_safety=drugged_no_safety,
        undrugged=undrugged,
    )


@router.get("/score-distribution", response_model=ScoreDistribution)
async def get_score_distribution():
    """Return pre-computed histogram of HumanProof safety scores for all genes,
    split by drugged+safety-event, drugged+no-safety-event, and undrugged."""
    return _compute_score_distribution()


@router.get("/search", response_model=list[GeneSearchResult])
async def search_genes(
    q: str = Query(..., min_length=1, description="Search query"),
    limit: int = Query(20, le=100),
    db: AsyncSession = Depends(get_db),
):
    query_upper = q.upper()

    # Get genes matching the query
    expr_result = await db.execute(
        select(
            ExpressionSummary.gene_symbol,
            ExpressionSummary.ensembl_id,
            func.count(distinct(ExpressionSummary.tissue)).label("n_tissues"),
        )
        .where(ExpressionSummary.gene_symbol.like(f"{query_upper}%"))
        .group_by(ExpressionSummary.gene_symbol, ExpressionSummary.ensembl_id)
        .limit(limit)
    )
    expr_rows = expr_result.all()

    results = []
    for gene_symbol, ensembl_id, n_tissues in expr_rows:
        # Count pLOF associations
        plof_count = await db.execute(
            select(func.count())
            .select_from(PLOFAssociation)
            .where(PLOFAssociation.gene_symbol == gene_symbol)
        )
        n_plof = plof_count.scalar() or 0

        # Get risk class: use DR model score (same logic as safety-card) with LOEUF fallback
        dosage = await db.execute(
            select(GeneDosageSensitivity.risk_class).where(
                GeneDosageSensitivity.gene_symbol == gene_symbol
            )
        )
        loeuf_risk_class = dosage.scalar() or "unknown"
        shap_entry = _load_shap_metadata().get(gene_symbol)
        risk_class = _dr_risk_class(shap_entry, loeuf_fallback=loeuf_risk_class)

        results.append(
            GeneSearchResult(
                gene_symbol=gene_symbol,
                ensembl_id=ensembl_id,
                n_tissues=n_tissues,
                n_plof_associations=n_plof,
                risk_class=risk_class,
            )
        )

    return results


@router.get("/{gene_symbol}/safety-card", response_model=SafetyCard)
async def get_safety_card(gene_symbol: str, db: AsyncSession = Depends(get_db)):
    gene_upper = gene_symbol.upper()

    # Get expression data
    expr_result = await db.execute(
        select(ExpressionSummary)
        .where(ExpressionSummary.gene_symbol == gene_upper)
        .order_by(ExpressionSummary.mean_expression.desc())
    )
    expr_rows = expr_result.scalars().all()
    if not expr_rows:
        raise HTTPException(status_code=404, detail=f"Gene {gene_upper} not found")

    ensembl_id = expr_rows[0].ensembl_id
    all_tissues = set(r.tissue for r in expr_rows)
    all_cell_types = set(r.cell_type for r in expr_rows)
    expressing_cells = [r for r in expr_rows if r.pct_expressed > 0.1]
    expressing_cell_types = set(r.cell_type for r in expressing_cells)
    expressing_tissues    = set(r.tissue   for r in expressing_cells)

    top_expr = expr_rows[0] if expr_rows else None
    expr_summary = ExpressionSummaryForCard(
        n_tissues=len(all_tissues),
        n_cell_types=len(all_cell_types),
        n_expressing_tissues=len(expressing_tissues),
        n_expressing_cell_types=len(expressing_cell_types),
        top_tissue=top_expr.tissue if top_expr else "N/A",
        top_cell_type=top_expr.cell_type if top_expr else "N/A",
        max_expression=top_expr.mean_expression if top_expr else 0.0,
        expression_breadth=len(expressing_cells) / len(expr_rows) if expr_rows else 0.0,
        top_entries=[
            CellTypeExpression(
                cell_type=r.cell_type,
                tissue=r.tissue,
                organ=r.organ,
                mean_expression=r.mean_expression,
                pct_expressed=r.pct_expressed,
                n_cells=r.n_cells,
            )
            for r in expr_rows[:10]  # Top 10
        ],
    )

    # Get pLOF data
    plof_result = await db.execute(
        select(PLOFAssociation)
        .where(PLOFAssociation.gene_symbol == gene_upper)
        .order_by(PLOFAssociation.p_value)
    )
    plof_rows = plof_result.scalars().all()
    sig_plof = [r for r in plof_rows if r.p_value < 5e-8]
    sug_plof = [r for r in plof_rows if 5e-8 <= r.p_value < 1e-5]
    # Organ systems: only from associations meeting at least suggestive threshold (p < 1e-5)
    organ_systems = sorted(set(
        r.organ_system for r in plof_rows if r.p_value < 1e-5
    ))

    plof_summary = PLOFSummaryForCard(
        n_associations=len(plof_rows),
        n_significant=len(sig_plof),
        n_suggestive=len(sug_plof),
        top_phenotype=plof_rows[0].phenotype if plof_rows else None,
        max_severity="benign",  # Will be overridden below
        organ_systems_affected=organ_systems,
        top_entries=[
            PLOFAssociationSchema(
                phenotype=r.phenotype,
                phenotype_category=r.phenotype_category,
                organ_system=r.organ_system,
                p_value=r.p_value,
                p_value_burden=r.p_value_burden,
                p_value_skat=r.p_value_skat,
                beta=r.beta,
                se=r.se,
                n_carriers=r.n_carriers,
                direction=r.direction,
            )
            for r in plof_rows[:10]
        ],
    )

    # Get dosage sensitivity
    dosage_result = await db.execute(
        select(GeneDosageSensitivity).where(
            GeneDosageSensitivity.gene_symbol == gene_upper
        )
    )
    dosage = dosage_result.scalar_one_or_none()
    dosage_schema = (
        GeneDosageSensitivitySchema(
            gene_symbol=dosage.gene_symbol,
            pli_score=dosage.pli_score,
            loeuf_score=dosage.loeuf_score,
            mis_z_score=dosage.mis_z_score,
            risk_class=dosage.risk_class,
        )
        if dosage
        else None
    )

    # Compute risk class
    from app.api.v1.plof import classify_severity

    severity = classify_severity(plof_rows, dosage)
    plof_summary.max_severity = severity

    # Load SHAP entry and extract clinical metadata
    shap_entry       = _load_shap_metadata().get(gene_upper)
    is_drugged       = bool(shap_entry.get("is_drugged", False)) if shap_entry else False
    clinical_phase   = shap_entry.get("clinical_phase")          if shap_entry else None
    has_safety_event = shap_entry.get("has_safety_event")        if shap_entry else None
    hp_model         = shap_entry["model"]                       if shap_entry else None

    # DR model provides valid scores for ALL genes (drugged and undrugged)
    hp_score = shap_entry["safety_score"] if shap_entry else None

    # Risk class: confirmed safety events override ML; otherwise use DR score
    risk_class = _dr_risk_class(shap_entry, loeuf_fallback=dosage.risk_class if dosage else "moderate")

    return SafetyCard(
        gene_symbol=gene_upper,
        ensembl_id=ensembl_id,
        risk_class=risk_class,
        humanproof_score=hp_score,
        humanproof_model=hp_model,
        is_drugged=is_drugged,
        clinical_phase=clinical_phase,
        has_safety_event=has_safety_event,
        expression_summary=expr_summary,
        plof_summary=plof_summary,
        dosage_sensitivity=dosage_schema,
    )


@router.get("/{gene_symbol}/safety-shap", response_model=GeneSHAP)
async def get_safety_shap(
    gene_symbol: str,
    n_features: int = Query(20, ge=1, le=191, description="Number of top features to return"),
):
    """Return per-gene SHAP values showing how each feature contributed to the
    HumanProof safety score. Features are sorted by |SHAP value| descending."""
    gene_upper = gene_symbol.upper()
    shap_meta  = _load_shap_metadata()

    if not shap_meta:
        raise HTTPException(
            status_code=503,
            detail="SHAP data not available. Run data/export_gene_shap.py first.",
        )

    entry = shap_meta.get(gene_upper)
    if entry is None:
        raise HTTPException(
            status_code=404,
            detail=f"No SHAP data for gene {gene_upper}. Gene may not be in the 108-gene panel.",
        )

    raw_features = _load_gene_features(gene_upper) or []
    features = [ShapFeature(**f) for f in raw_features[:n_features]]

    return GeneSHAP(
        gene_symbol=gene_upper,
        ensembl_id=entry["ensembl_id"],
        safety_score=entry["safety_score"],
        base_value=entry["base_value"],
        model=entry["model"],
        safety_label=entry["safety_label"],
        features=features,
    )
